In [ ]:
import numpy as np
from numpy import sys
np.set_printoptions(threshold=sys.maxsize)
from scipy.signal import savgol_filter
from scipy.signal import find_peaks
from scipy import stats
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, ShuffleSplit, cross_val_score
from sklearn import svm
import pandas as pd
import sys
import os
import matplotlib
matplotlib.use("TkAgg")
from matplotlib import pyplot as plt   
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg #, NavigationToolbar2TkAgg
from matplotlib.figure import Figure

import csv

In [1]:
# 22.04.08: Stress classification training data
# 22.04.07 : Concentration classification training data
# 22.05.19 : dominant species classification tratining data

#22.06.25_pond_stress : stess classification field sample test data
#22.06.23_pond_conc : concentration classification field sample test data

#22.05.23 : Weak indoor ambient light condition
#22.05.25: Strong indoor ambient light conditoin
#22.05.28: Weak outdoor ambient light condition

In [ ]:
data_file1 = '22.04.08_Acryl_Stress.csv'
data_file2 = '22.04.07_acryl_concentration.csv'
data_file3 = '22.05.19.csv'
data_file1_ = '22.05.28_Stress.csv'
data_file2_ = '22.05.28_Conc.csv'
data_file3_ = '22.05.28_Dominant.csv'
accuracy_threshold= -1

In [3]:
df1 = pd.read_csv(data_file1)
df2 = pd.read_csv(data_file2)
df3 = pd.read_csv(data_file3)
df1_ = pd.read_csv(data_file1_)
df2_ = pd.read_csv(data_file2_)
df3_ = pd.read_csv(data_file3_)


In [4]:
y1 =df1.loc[:,'Name'].values
x1 =df1.drop(['Name'],axis=1)

y2 =df2.loc[:,'Name'].values
x2 =df2.drop(['Name'],axis=1)

y3 =df3.loc[:,'Name'].values
x3 =df3.drop(['Name'],axis=1)

y1_ =df1_.loc[:,'Name'].values
x1_ =df1_.drop(['Name'],axis=1)

y2_ =df2_.loc[:,'Name'].values
x2_ =df2_.drop(['Name'],axis=1)

y3_ =df3_.loc[:,'Name'].values
x3_ =df3_.drop(['Name'],axis=1)


In [5]:
X1=np.asarray(x1)
Y1=np.asarray(y1)

X2=np.asarray(x2)
Y2=np.asarray(y2)

X3=np.asarray(x3)
Y3=np.asarray(y3)

X1_=np.asarray(x1_)
Y1_=np.asarray(y1_)

X2_=np.asarray(x2_)
Y2_=np.asarray(y2_)

X3_=np.asarray(x3_)
Y3_=np.asarray(y3_)


In [6]:
    for b in range(-300,300,10):
        for gam in (0.01, 0.01, 0.1, 1, 10):
             for c in (0.01, 0.01, 0.1, 1, 10):
                for ker in ('poly', 'linear', 'rbf'): 
        

                    k=X1_ +b

                    #Grid search
                    classifier1 = svm.SVC(kernel=ker,gamma=gam,C=c)

                    # Run the classifier for ALL PCs to predict the Test data
                    y_pred1 = classifier1.fit(X1,Y1).predict(k)
                 
                    accuracy1 = accuracy_score(y1_, y_pred1)

                    print(b, gam,c, ker, accuracy1)

-10 -10 0.01 0.01 poly 0.0
-10 -10 0.01 0.01 linear 0.0
-10 -10 0.01 0.01 rbf 0.0
-10 -10 0.01 0.01 poly 0.0
-10 -10 0.01 0.01 linear 0.0
-10 -10 0.01 0.01 rbf 0.0
-10 -10 0.1 0.01 poly 0.0
-10 -10 0.1 0.01 linear 0.0
-10 -10 0.1 0.01 rbf 0.0
-10 -10 1 0.01 poly 0.0
-10 -10 1 0.01 linear 0.0
-10 -10 1 0.01 rbf 0.0
-10 -10 10 0.01 poly 0.0
-10 -10 10 0.01 linear 0.0
-10 -10 10 0.01 rbf 0.0
-10 -10 0.01 0.01 poly 0.0
-10 -10 0.01 0.01 linear 0.0
-10 -10 0.01 0.01 rbf 0.0
-10 -10 0.01 0.01 poly 0.0
-10 -10 0.01 0.01 linear 0.0
-10 -10 0.01 0.01 rbf 0.0
-10 -10 0.1 0.01 poly 0.0
-10 -10 0.1 0.01 linear 0.0
-10 -10 0.1 0.01 rbf 0.0
-10 -10 1 0.01 poly 0.0
-10 -10 1 0.01 linear 0.0
-10 -10 1 0.01 rbf 0.0
-10 -10 10 0.01 poly 0.0
-10 -10 10 0.01 linear 0.0
-10 -10 10 0.01 rbf 0.0
-10 -10 0.01 0.1 poly 0.0
-10 -10 0.01 0.1 linear 0.0
-10 -10 0.01 0.1 rbf 0.0
-10 -10 0.01 0.1 poly 0.0
-10 -10 0.01 0.1 linear 0.0
-10 -10 0.01 0.1 rbf 0.0
-10 -10 0.1 0.1 poly 0.0
-10 -10 0.1 0.1 linear 0.0
-10 -1

KeyboardInterrupt: 

In [34]:
from sklearn import svm
k= X1_-41
classifier = svm.SVC(kernel='linear',gamma=0.1,C=0.1)
classifier.fit(X1,Y1)

y1_predict=classifier.predict(k)

In [35]:
from sklearn.metrics import classification_report

print(classification_report(Y1_,y1_predict))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        10
           2       0.07      0.20      0.10        10
           3       0.00      0.00      0.00        10
           4       0.11      0.10      0.11        10

    accuracy                           0.07        40
   macro avg       0.04      0.08      0.05        40
weighted avg       0.04      0.07      0.05        40



C:\Users\schac\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [37]:
from sklearn.metrics import confusion_matrix

#Generate the confusion matrix
cf_matrix = confusion_matrix(Y1_, y1_predict)

print(cf_matrix)

[[ 0 10  0  0]
 [ 0  2  0  8]
 [ 1  9  0  0]
 [ 0  9  0  1]]


In [ ]:
import seaborn as sns

ax = sns.heatmap(cf_matrix, annot=True, cmap='Blues')

ax.set_title('Seaborn Confusion Matrix with labels\n\n');
ax.set_xlabel('\nPredicted Values')
ax.set_ylabel('Actual Values ');

## Ticket labels - List must be in alphabetical order
ax.xaxis.set_ticklabels(['Green','Red','Brown','Even'])
ax.yaxis.set_ticklabels(['Green','Red','Brown','Even'])

## Display the visualization of the Confusion Matrix.
plt.show()